spring.application.name=demo

spring.data.mongodb.uri=${MONGODB_URI:mongodb://127.0.0.1:27017/eventdb?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000}
server.port=8080

# Enable throwing NoHandlerFoundException for missing mappings
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
